export enum NodeType {
    INITIAL = "INITIAL",
    MANUAL_TRIGGER = "MANUAL_TRIGGER",
    HTTP_REQUEST = "HTTP_REQUEST",
    GOOGLE_FORM_TRIGGER = "GOOGLE_FORM_TRIGGER",
    STRIPE_TRIGGER = "STRIPE_TRIGGER",
    GEMINI = "GEMINI",
    OPENAI = "OPENAI",
    ANTHROPIC = "ANTHROPIC",
    DISCORD = "DISCORD",
    SLACK = "SLACK",
}
